baseURL: 'https://build.wilder.wp.computer/'
title: 'ğœ”Ã—ğ›¼: â¦§ğ˜–â€‘ğ˜–$ !WILDERANDAURORA'

# Uncomment when not installing with Hugo Modules
# theme: eureka
# Comment when not installing with Hugo Modules
theme: wangchucheng.com/hugo-eureka
# If you cannot access the Github mirror, you can also use the Gitee mirror: gitee.com/wangchucheng/hugo-eureka

paginate: 20
copyright: 'âˆ€âˆƒ!â=â¨Šâ€(âƒâ¨Ÿ$[â˜®]) ~ &trade;|&copy;|â˜¢â˜ â˜£ ~ 1996-2025++ ~ past|present|future
<br>
<br>
The Wilder-ness Adventures ~ The Wilder-ness, World Piece Computer, LLC, dba Wilder WPC ~ World Peacebrain Mindeye V1 ~ Time Machine For Peace Social Invention Program ~ {world piece, world piece computer, the universal piece, the universal piece computer} + General Peace Dynamics + A Study In Peace: (Operator`s Manual For The Timespace Matter Mindmachine) + WilderÃ—Aurora
<br>
<br>
This effort is dedicated to victims of, those currently suffering from, and those otherwise lost to generalized war.
<br>
<br>
'

enableGitInfo: false
summaryLength: 75

defaultContentLanguage: en
hasCJKLanguage: false # Set `true` for Chinese/Japanese/Korean.
defaultContentLanguageInSubdir: false

# Uncomment for google analytics
# googleAnalytics: UA-123-45

markup:
  # Do not modify markup.highlight
  highlight:
    codeFences: false
    noClasses: false
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false
  goldmark:
    renderer:
      unsafe: true

taxonomies:
  category: categories
  tag: tags
  series: series
  author: authors

build:
  useResourceCacheWhen: always


